import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Providers } from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="bg-gradient-to-br from-background to-muted">
            <Header/>
            <main className="conatainer min-h-screen mx-auto px-4 py-8">
              {children}  
            </main>
            <footer className="pt-4  border-t supports-[backdrop-filter]:bg-background/60">
              <p className="text-sm text-center py-5 mx-auto text-gray-500">
                &copy; 2025 Weather4U. All rights reserved.
              </p>
            </footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
